### ISSUE TITLE
Make it possible to do both a Prefix and a Postfix hook for a given method

### ISSUE THREAD

**Issue by tyr7z** [nsfury/UnityWebModkit#1]
The title says it all to be honest.

**Comment by tyr7z** [comment]
Also make it work between multiple scripts.

**Comment by nsfury** [comment]
So, I thought I didn't add support for this yet but after some testing, it seems to already be working. The system already fully supports multiple prefixes/postfixes on the same method, and it works across multiple plugins (or multiple UserScripts).
